### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by traincrisis** [0razec/Erekir-Mods#2]
I think you should add Erekir Extended and Erekir Reworked into this modpack since they add some cool vanilla-styled stuff.

**Comment by 0razec** [comment]
Absolutely! After developers validation of these technologies, I will consider merging the suggested mods into the modpack. Until then, I will resume my archived projects from five months ago. Thank you for your feedback and suggestion!

**Comment by traincrisis** [comment]
when youll add these

**Comment by 0razec** [comment]
I am finally preparing the ChangeLogs, in which you can see the progress and changes in more detail of this project, my forecast is until Sunday  :)

**Comment by traincrisis** [comment]
Still no update? When whennnnnnn
